# -*- coding: utf-8 -*-
"""CodeTutor 评估用例集(40 例)。

字段:
  name              用例名
  code              问题代码
  symptom           学生的问题描述
  expect_error_type 期望诊断出的错误类型
  expect_stdout     修复后正确代码的精确输出(None 表示开放修复)
  check_mode        "stdout"=严格比对输出 / "no_error"=运行无报错即可

分组:A 报错类(1-20)/ B 逻辑类(21-35,结果错但不报错)/ C 综合类(36-40)
"""

CASES = [
    # ============ A 组:运行时报错类 ============
    {
        "name": "A01 列表索引越界",
        "code": "scores = [85, 92, 78]\ntotal = 0\nfor i in range(len(scores) + 1):\n    total += scores[i]\nprint(total)\n",
        "symptom": "运行报错:IndexError: list index out of range",
        "expect_error_type": "IndexError",
        "expect_stdout": "255",
        "check_mode": "stdout",
    },
    {
        "name": "A02 字典键不存在",
        "code": "student = {'name': '小明', 'age': 20}\nprint(student['name'])\nprint(student['score'])\n",
        "symptom": "运行报错:KeyError: 'score'",
        "expect_error_type": "KeyError",
        "expect_stdout": None,
        "check_mode": "no_error",
    },
    {
        "name": "A03 字符串数字混合运算",
        "code": "price = '100'\ncount = 3\ntotal = int(price) * count\nprint('总价:', total + 0.0)\n",
        "symptom": "报错 TypeError,我想算总价",
        "expect_error_type": "TypeError",
        "expect_stdout": None,  # int(price)*count 已修一半,观察模型如何处理
        "check_mode": "no_error",
    },
    {
        "name": "A04 sort() 返回值误用",
        "code": "nums = [3, 1, 2]\nsorted_nums = nums.sort()\nprint('最小值:', sorted_nums[0])\n",
        "symptom": "报错:TypeError: 'NoneType' object is not subscriptable",
        "expect_error_type": "TypeError",
        "expect_stdout": "最小值: 1",
        "check_mode": "stdout",
    },
    {
        "name": "A05 递归缺少基例",
        "code": "def factorial(n):\n    return n * factorial(n - 1)\n\nprint(factorial(5))\n",
        "symptom": "运行报错:RecursionError: maximum recursion depth exceeded",
        "expect_error_type": "RecursionError",
        "expect_stdout": "120",
        "check_mode": "stdout",
    },
    {
        "name": "A06 除零错误",
        "code": "def average(nums):\n    return sum(nums) / len(nums)\n\nprint(average([90, 80]))\nprint(average([]))\n",
        "symptom": "第二个调用报错:ZeroDivisionError: division by zero",
        "expect_error_type": "ZeroDivisionError",
        "expect_stdout": ["85.0\n0", "85.0\n0.0"],  # 返回 0 或 0.0 均为合理修复
        "check_mode": "stdout",
    },
    {
        "name": "A07 变量未定义",
        "code": "def greet():\n    return '你好, ' + name\n\nname = '小明'\nprint(greet())\n",
        "symptom": "这个能运行吗?帮我检查\n实际报错:NameError name 未定义的情况",
        "expect_error_type": None,  # 开放:这段代码其实能运行(全局变量可读)
        "expect_stdout": "你好, 小明",
        "check_mode": "stdout",
    },
    {
        "name": "A08 对 None 调用 append",
        "code": "items = None\nitems.append(1)\nprint(items)\n",
        "symptom": "报错:AttributeError: 'NoneType' object has no attribute 'append'",
        "expect_error_type": "AttributeError",
        "expect_stdout": "[1]",
        "check_mode": "stdout",
    },
    {
        "name": "A09 缩进错误",
        "code": "def say_hi():\nprint('hi')\n\nsay_hi()\n",
        "symptom": "报错:IndentationError: expected an indented block",
        "expect_error_type": "IndentationError",
        "expect_stdout": "hi",
        "check_mode": "stdout",
    },
    {
        "name": "A10 字符串不可变修改",
        "code": "s = 'abc'\ns[0] = 'X'\nprint(s)\n",
        "symptom": "想把首字母改成 X,报错 TypeError",
        "expect_error_type": "TypeError",
        "expect_stdout": "Xbc",
        "check_mode": "stdout",
    },
    {
        "name": "A11 int() 转换失败",
        "code": "num = int('12.5')\nprint(num)\n",
        "symptom": "报错:ValueError: invalid literal for int()",
        "expect_error_type": "ValueError",
        "expect_stdout": None,
        "check_mode": "no_error",
    },
    {
        "name": "A12 对整数取 len",
        "code": "n = 12345\nprint(len(n))\n",
        "symptom": "想知道数字有几位,报错 TypeError",
        "expect_error_type": "TypeError",
        "expect_stdout": "5",
        "check_mode": "stdout",
    },
    {
        "name": "A13 空列表取首元素",
        "code": "lst = []\nprint(lst[0])\n",
        "symptom": "报错 IndexError,列表可能为空",
        "expect_error_type": "IndexError",
        "expect_stdout": None,
        "check_mode": "no_error",
    },
    {
        "name": "A14 函数内修改全局变量",
        "code": "count = 0\n\ndef inc():\n    count += 1\n    return count\n\nprint(inc())\n",
        "symptom": "报错:UnboundLocalError",
        "expect_error_type": "UnboundLocalError",
        "expect_stdout": None,
        "check_mode": "no_error",
    },
    {
        "name": "A15 字符串拼接整数",
        "code": "age = 20\nprint('年龄: ' + age)\n",
        "symptom": "报错:TypeError: can only concatenate str",
        "expect_error_type": "TypeError",
        "expect_stdout": "年龄: 20",
        "check_mode": "stdout",
    },
    {
        "name": "A16 format 参数不足",
        "code": "print('{}-{}'.format('a'))\n",
        "symptom": "报错 IndexError: Replacement index 1 out of range",
        "expect_error_type": "IndexError",
        "expect_stdout": None,
        "check_mode": "no_error",
    },
    {
        "name": "A17 修改元组元素",
        "code": "t = (1, 2, 3)\nt[0] = 9\nprint(t)\n",
        "symptom": "想把第一个元素改成 9,报错 TypeError",
        "expect_error_type": "TypeError",
        "expect_stdout": None,
        "check_mode": "no_error",
    },
    {
        "name": "A18 字典键大小写错误",
        "code": "d = {'name': '小明'}\nprint(d['Name'])\n",
        "symptom": "报错 KeyError: 'Name'",
        "expect_error_type": "KeyError",
        "expect_stdout": "小明",
        "check_mode": "stdout",
    },
    {
        "name": "A19 变量遮蔽内置函数",
        "code": "list = [1, 2, 3]\nprint(list)\nnew_list = list(range(3))\nprint(new_list)\n",
        "symptom": "第三行报错:TypeError: 'list' object is not callable",
        "expect_error_type": "TypeError",
        "expect_stdout": "[1, 2, 3]\n[0, 1, 2]",
        "check_mode": "stdout",
    },
    {
        "name": "A20 字典遍历时删除",
        "code": "d = {'a': 1, 'b': 2, 'c': 3}\nfor k in d:\n    if d[k] % 2 == 0:\n        del d[k]\nprint(d)\n",
        "symptom": "报错:RuntimeError: dictionary changed size during iteration",
        "expect_error_type": "RuntimeError",
        "expect_stdout": "{'a': 1, 'c': 3}",
        "check_mode": "stdout",
    },
    # ============ B 组:逻辑错误类(不报错但结果错) ============
    {
        "name": "B01 可变默认参数陷阱",
        "code": "def add_item(item, box=[]):\n    box.append(item)\n    return box\n\nprint(add_item(1))\nprint(add_item(2))\n",
        "symptom": "第二次调用期望返回 [2],实际返回 [1, 2],数据串了",
        "expect_error_type": "LogicError",
        "expect_stdout": "[1]\n[2]",
        "check_mode": "stdout",
    },
    {
        "name": "B02 遍历时删除列表元素",
        "code": "nums = [1, 2, 3, 4, 5, 6]\nfor n in nums:\n    if n % 2 == 0:\n        nums.remove(n)\nprint(nums)\n",
        "symptom": "想删掉所有偶数,结果输出 [1, 3, 4, 5],4 没删掉",
        "expect_error_type": "LogicError",
        "expect_stdout": "[1, 3, 5]",
        "check_mode": "stdout",
    },
    {
        "name": "B03 列表别名而非拷贝",
        "code": "origin = [1, 2, 3]\nbackup = origin\nbackup[0] = 99\nprint('原列表:', origin)\n",
        "symptom": "我只改了 backup,为什么 origin 也变成了 [99, 2, 3]?",
        "expect_error_type": "LogicError",
        "expect_stdout": "原列表: [1, 2, 3]",
        "check_mode": "stdout",
    },
    {
        "name": "B04 差一错误",
        "code": "def first_n_squares(n):\n    squares = []\n    for i in range(1, n):\n        squares.append(i * i)\n    return squares\n\nprint(first_n_squares(5))\n",
        "symptom": "想要前 5 个平方数 [1,4,9,16,25],结果只有 4 个",
        "expect_error_type": "LogicError",
        "expect_stdout": "[1, 4, 9, 16, 25]",
        "check_mode": "stdout",
    },
    {
        "name": "B05 is 与 == 混用",
        "code": "a = [1, 2]\nb = [1, 2]\nif a is b:\n    print('内容相同')\nelse:\n    print('内容不同')\n",
        "symptom": "两个列表内容明明一样,为什么输出'内容不同'?",
        "expect_error_type": "LogicError",
        "expect_stdout": "内容相同",
        "check_mode": "stdout",
    },
    {
        "name": "B06 整数除法误用",
        "code": "result = 7 // 2\nprint(result)\n",
        "symptom": "7 除以 2 应该是 3.5,为什么输出 3?",
        "expect_error_type": "LogicError",
        "expect_stdout": "3.5",
        "check_mode": "stdout",
    },
    {
        "name": "B07 类变量被所有实例共享",
        "code": "class Student:\n    courses = []\n    def add(self, c):\n        self.courses.append(c)\n\ns1 = Student()\ns1.add('数学')\ns2 = Student()\nprint(len(s2.courses))\n",
        "symptom": "s2 是新学生,一门课都没选,为什么输出 1?",
        "expect_error_type": "LogicError",
        "expect_stdout": "0",
        "check_mode": "stdout",
    },
    {
        "name": "B08 字符串 replace 未接收返回值",
        "code": "s = 'hello'\ns.replace('h', 'H')\nprint(s)\n",
        "symptom": "想把 h 换成 H,为什么还是输出 hello?",
        "expect_error_type": "LogicError",
        "expect_stdout": "Hello",
        "check_mode": "stdout",
    },
    {
        "name": "B09 return 缩进位置错误",
        "code": "def find_first_even(nums):\n    for n in nums:\n        if n % 2 == 0:\n            return n\n        return None\n\nprint(find_first_even([1, 3, 4]))\n",
        "symptom": "列表里明明有偶数 4,为什么返回 None?",
        "expect_error_type": "LogicError",
        "expect_stdout": "4",
        "check_mode": "stdout",
    },
    {
        "name": "B10 最大值初始值错误",
        "code": "def max_of(nums):\n    m = 0\n    for n in nums:\n        if n > m:\n            m = n\n    return m\n\nprint(max_of([-5, -2, -9]))\n",
        "symptom": "最大值应该是 -2,为什么输出 0?",
        "expect_error_type": "LogicError",
        "expect_stdout": "-2",
        "check_mode": "stdout",
    },
    {
        "name": "B11 闭包捕获循环变量",
        "code": "funcs = [lambda: i for i in range(3)]\nprint([f() for f in funcs])\n",
        "symptom": "期望输出 [0, 1, 2],为什么是 [2, 2, 2]?",
        "expect_error_type": "LogicError",
        "expect_stdout": "[0, 1, 2]",
        "check_mode": "stdout",
    },
    {
        "name": "B12 空列表布尔判断",
        "code": "def check(lst):\n    if lst == False:\n        print('空')\n    else:\n        print('非空')\n\ncheck([])\n",
        "symptom": "传入空列表应该输出'空',为什么输出'非空'?",
        "expect_error_type": "LogicError",
        "expect_stdout": "空",
        "check_mode": "stdout",
    },
    {
        "name": "B13 累乘初始值为 0",
        "code": "def factorial(n):\n    r = 0\n    for i in range(1, n + 1):\n        r *= i\n    return r\n\nprint(factorial(5))\n",
        "symptom": "5 的阶乘应该是 120,为什么输出 0?",
        "expect_error_type": "LogicError",
        "expect_stdout": "120",
        "check_mode": "stdout",
    },
    {
        "name": "B14 嵌套列表浅拷贝",
        "code": "matrix = [[0] * 3] * 3\nmatrix[0][0] = 1\nprint(matrix)\n",
        "symptom": "只想改第一行第一个,为什么三行都变了?",
        "expect_error_type": "LogicError",
        "expect_stdout": "[[1, 0, 0], [0, 0, 0], [0, 0, 0]]",
        "check_mode": "stdout",
    },
    {
        "name": "B15 循环内重复初始化累加器",
        "code": "def row_sums(table):\n    result = []\n    for row in table:\n        total = 0\n        for x in row:\n            total += x\n        result.append(total)\n    return result\n\nprint(row_sums([[1, 2], [3, 4]]))\n",
        "symptom": "检查这个求每行和的函数对不对",
        "expect_error_type": None,  # 这段是对的,考察是否误诊
        "expect_stdout": "[3, 7]",
        "check_mode": "stdout",
    },
    # ============ C 组:综合/多错误 ============
    {
        "name": "C01 冒泡排序边界错误",
        "code": "def bubble_sort(arr):\n    n = len(arr)\n    for i in range(n):\n        for j in range(n - 1):\n            if arr[j] > arr[j + 1]:\n                arr[j], arr[j + 1] = arr[j + 1], arr[j]\n    return arr\n\nprint(bubble_sort([5, 2, 9, 1, 3]))\n",
        "symptom": "检查这个冒泡排序对不对,输出 [1, 2, 3, 5, 9] 吗?",
        "expect_error_type": None,  # 正确代码,考察是否误诊
        "expect_stdout": "[1, 2, 3, 5, 9]",
        "check_mode": "stdout",
    },
    {
        "name": "C02 双错误混合",
        "code": "nums = [10, 20, 30]\ntotal = 0\nfor i in range(len(nums) + 1):\n    total += nums[i]\nprint('总和: ' + total)\n",
        "symptom": "代码报错,帮我修好,最后要输出总和",
        "expect_error_type": "IndexError",
        "expect_stdout": "总和: 60",
        "check_mode": "stdout",
    },
    {
        "name": "C03 字符串格式化类型错误",
        "code": "score = 95.5\nprint('得分: %d' % score)\n",
        "symptom": "想保留小数输出 95.5,输出却是 95",
        "expect_error_type": "LogicError",
        "expect_stdout": ["得分: 95.5", "得分:95.5", "得分: 95.500000", "得分:95.500000"],
        "check_mode": "stdout",
    },
    {
        "name": "C04 计数器未正确累加",
        "code": "def count_even(nums):\n    count = 0\n    for n in nums:\n        if n % 2 == 0:\n            count + 1\n    return count\n\nprint(count_even([1, 2, 3, 4]))\n",
        "symptom": "偶数有 2 个,为什么返回 0?",
        "expect_error_type": "LogicError",
        "expect_stdout": "2",
        "check_mode": "stdout",
    },
    {
        "name": "C05 找最大值索引错误",
        "code": "def index_of_max(nums):\n    idx = 0\n    for i in range(len(nums)):\n        if nums[i] > nums[idx]:\n            idx = i\n    return idx\n\nprint(index_of_max([3, 9, 5]))\n",
        "symptom": "检查这个函数能正确返回最大值下标吗",
        "expect_error_type": None,  # 正确代码
        "expect_stdout": "1",
        "check_mode": "stdout",
    },
]
